trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'AzureResourceGroup-WebApp-SQL'
    Contents: '*.json'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(Build.ArtifactStagingDirectory)'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Web-App-RG-ServiceConnection'
    subscriptionId: '68d85a76-5f53-4179-8124-39b19bd950ee'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'web-app-rg1'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: '$(Build.ArtifactStagingDirectory)/drop/WebSiteSQLDatabase.json'
    csmParametersFileLink: '$(Build.ArtifactStagingDirectory)/drop/WebSiteSQLDatabase.parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'deploy1'