trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'AzureResourceGroup-WebApp-SQL'
    Contents: '*.json'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)'
    azureSubscription: 'Azure Free Basic(68d85a76-5f53-4179-8124-39b19bd950ee)'
    Destination: 'AzureBlob'
    storage: 'armstorageasa'
    ContainerName: 'templates'
    BlobPrefix: 'build_$(Release.ReleaseId)'
    AdditionalArgumentsForBlobCopy: '/Pattern:"*.json" /Y'
    outputStorageUri: TemplatesUrl
    outputStorageContainerSasToken: TemplatesSASToken
    CleanTargetBeforeCopy: true
    sasTokenTimeOutInMinutes: '30'
  name: AzureFileCopy

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo '$(AzureFileCopy.TemplatesUrl)'
      echo '$(AzureFileCopy.TemplatesSASToken)'
 
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure Free Basic(68d85a76-5f53-4179-8124-39b19bd950ee)'
    subscriptionId: '68d85a76-5f53-4179-8124-39b19bd950ee'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'arm-storage-rg'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: '$(AzureFileCopy.TemplatesUrl)WebSiteSQLDatabase.json$(AzureFileCopy.TemplatesSASToken)'
    csmParametersFileLink: '$(AzureFileCopy.TemplatesUrl)WebSiteSQLDatabase.parameters.json$(AzureFileCopy.TemplatesSASToken)'
    deploymentMode: 'Incremental'
    deploymentName: 'deploy1'